import { Category } from '../models';

// Default Hebrew categories for personal household and committee management
// These will be inserted into the database on first launch

export const defaultCategories: Omit<Category, 'id'>[] = [
  // ========== הכנסות (Income) ==========
  {
    name_he: 'משכורת',
    name_en: 'Salary',
    type: 'income',
    icon: 'wallet',
    color: '#4CAF50',
    is_default: true,
  },
  {
    name_he: 'הכנסה נוספת',
    name_en: 'Additional Income',
    type: 'income',
    icon: 'cash-multiple',
    color: '#8BC34A',
    is_default: true,
  },
  {
    name_he: 'דמי שכירות',
    name_en: 'Rental Income',
    type: 'income',
    icon: 'home-currency-usd',
    color: '#66BB6A',
    is_default: true,
  },
  {
    name_he: 'דמי ועד שנגבו',
    name_en: 'Committee Fees Collected',
    type: 'income',
    icon: 'bank-transfer-in',
    color: '#43A047',
    is_default: true,
  },

  // ========== הוצאות משק בית (Household Expenses) ==========
  {
    name_he: 'מכולת וסופרמרקט',
    name_en: 'Groceries & Supermarket',
    type: 'expense',
    icon: 'cart',
    color: '#FF5722',
    is_default: true,
  },
  {
    name_he: 'חשמל',
    name_en: 'Electricity',
    type: 'expense',
    icon: 'lightning-bolt',
    color: '#FFC107',
    is_default: true,
  },
  {
    name_he: 'מים',
    name_en: 'Water',
    type: 'expense',
    icon: 'water',
    color: '#2196F3',
    is_default: true,
  },
  {
    name_he: 'ארנונה',
    name_en: 'Municipal Tax',
    type: 'expense',
    icon: 'home-city',
    color: '#9C27B0',
    is_default: true,
  },
  {
    name_he: 'גז',
    name_en: 'Gas',
    type: 'expense',
    icon: 'fire',
    color: '#FF9800',
    is_default: true,
  },
  {
    name_he: 'אינטרנט',
    name_en: 'Internet',
    type: 'expense',
    icon: 'wifi',
    color: '#00BCD4',
    is_default: true,
  },
  {
    name_he: 'טלפון',
    name_en: 'Phone',
    type: 'expense',
    icon: 'phone',
    color: '#009688',
    is_default: true,
  },
  {
    name_he: 'ביטוח',
    name_en: 'Insurance',
    type: 'expense',
    icon: 'shield-check',
    color: '#673AB7',
    is_default: true,
  },
  {
    name_he: 'תחבורה ודלק',
    name_en: 'Transportation & Fuel',
    type: 'expense',
    icon: 'car',
    color: '#795548',
    is_default: true,
  },
  {
    name_he: 'בריאות ותרופות',
    name_en: 'Health & Medication',
    type: 'expense',
    icon: 'medical-bag',
    color: '#E91E63',
    is_default: true,
  },
  {
    name_he: 'חינוך',
    name_en: 'Education',
    type: 'expense',
    icon: 'school',
    color: '#3F51B5',
    is_default: true,
  },
  {
    name_he: 'בילויים ופנאי',
    name_en: 'Entertainment & Leisure',
    type: 'expense',
    icon: 'movie',
    color: '#E91E63',
    is_default: true,
  },
  {
    name_he: 'מסעדות וקפה',
    name_en: 'Restaurants & Coffee',
    type: 'expense',
    icon: 'food',
    color: '#F44336',
    is_default: true,
  },
  {
    name_he: 'ביגוד והנעלה',
    name_en: 'Clothing & Shoes',
    type: 'expense',
    icon: 'tshirt-crew',
    color: '#9C27B0',
    is_default: true,
  },
  {
    name_he: 'דמי ועד',
    name_en: 'Committee Fees',
    type: 'expense',
    icon: 'office-building',
    color: '#607D8B',
    is_default: true,
  },

  // ========== הוצאות ועד בית (Committee Expenses) ==========
  {
    name_he: 'ניקיון',
    name_en: 'Cleaning',
    type: 'expense',
    icon: 'broom',
    color: '#00BCD4',
    is_default: true,
  },
  {
    name_he: 'אבטחה',
    name_en: 'Security',
    type: 'expense',
    icon: 'shield-account',
    color: '#F44336',
    is_default: true,
  },
  {
    name_he: 'תחזוקה ותיקונים',
    name_en: 'Maintenance & Repairs',
    type: 'expense',
    icon: 'tools',
    color: '#FF9800',
    is_default: true,
  },
  {
    name_he: 'שיפוצים',
    name_en: 'Renovations',
    type: 'expense',
    icon: 'hammer-screwdriver',
    color: '#795548',
    is_default: true,
  },
  {
    name_he: 'גינון',
    name_en: 'Gardening',
    type: 'expense',
    icon: 'flower',
    color: '#4CAF50',
    is_default: true,
  },
  {
    name_he: 'חשמל משותף',
    name_en: 'Common Area Electricity',
    type: 'expense',
    icon: 'lightbulb',
    color: '#FFEB3B',
    is_default: true,
  },
  {
    name_he: 'מים משותפים',
    name_en: 'Common Area Water',
    type: 'expense',
    icon: 'water-pump',
    color: '#2196F3',
    is_default: true,
  },
  {
    name_he: 'ניהול ומינהל',
    name_en: 'Management & Administration',
    type: 'expense',
    icon: 'file-document',
    color: '#9E9E9E',
    is_default: true,
  },
  {
    name_he: 'ביטוח משותף',
    name_en: 'Building Insurance',
    type: 'expense',
    icon: 'shield-home',
    color: '#673AB7',
    is_default: true,
  },
];
